### ISSUE TITLE
No Terminator windows found

### ISSUE THREAD

**Issue by kylekirkby** [ilkka/consular-terminator#2]
Hi @ilkka,

I'm getting this error -

➜ consular start websites.yml
XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)
xdo_get_active_window reported an error
No Terminator windows found
kyle@gibson 

Any ideas? I 100% have a terminator window running...

Many thanks and BR,

Kyle

**Comment by ilkka** [comment]
Hey, unfortunately I haven't got a clue. Haven't touched this stuff in years, and right now don't even have a machine that would run terminator.

**Comment by kylekirkby** [comment]
Hey - no problem - thanks anyway! :100:
